# Site settings
title: Rion Hutsell # site title
description: >- # site description
  Software engineer relating what I've learned about web technology, blockchain, communication, music, and art.
lang: en-US # default lang
timezone: America/Denver # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/sciencefixion/sciencefixion.github.io # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Rion Hutsell # author name
  bio: >- # tell to the world
    Software engineer, writer, musician, and amateur philosopher sharing my experiences and discoveries in web technology, blockchain, and communication.
    <hr>
    See some of my code <a href="https://github.com/sciencefixion" target="_blank" rel="noopener">@github</a>.
  username: sciencefixion # general username
  github: sciencefixion # github username
  twitter: sciencefixi0n # twitter username
  # facebook: facebook_username # facebook username
  email: sciencefixion@pm.me # email adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://sciencefixion.github.io" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  portfolio:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false
  - scope:
      path: ""
      type: "portfolio"
      values:
        layout: "post"
        comments: false

# Jekyll Compose default front matter
jekyll_compose:
  auto_open: true
  post_default_front_matter:
    modified:
    tags: []
    description:
    published: false
    sitemap: false
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-postfiles
